import { NextRequest } from "next/server";

export async function GET(req: NextRequest) {
  try {
    const [helpers, { prisma }] = await Promise.all([
      import("@/lib/api-helpers"),
      import("@/lib/prisma"),
    ]);
    const { requireAdmin } = await import("@/lib/api-helpers");
    await requireAdmin(req);

    await prisma.$executeRawUnsafe(`ALTER TABLE events ADD COLUMN IF NOT EXISTS view_count INTEGER NOT NULL DEFAULT 0`);

    const now = new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const thirtyDaysAgo = new Date(today);
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    const sevenDaysAgo = new Date(today);
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    const [
      totalEvents,
      pendingEvents,
      approvedEvents,
      rejectedEvents,
      autoEvents,
      manualEvents,
      totalUsers,
      publishers,
      admins,
      totalSaved,
      totalAdClicks,
      totalViews,
    ] = await Promise.all([
      prisma.event.count(),
      prisma.event.count({ where: { status: "pending" } }),
      prisma.event.count({ where: { status: "approved" } }),
      prisma.event.count({ where: { status: "rejected" } }),
      prisma.event.count({ where: { isAutoGenerated: true } }),
      prisma.event.count({ where: { isAutoGenerated: false } }),
      prisma.user.count(),
      prisma.user.count({ where: { role: "publisher" } }),
      prisma.user.count({ where: { role: { in: ["admin", "super_admin"] } } }),
      prisma.savedEvent.count(),
      prisma.ad.aggregate({ _sum: { clickCount: true } }).then(r => r._sum.clickCount ?? 0),
      prisma.event.aggregate({ _sum: { viewCount: true } }).then(r => r._sum.viewCount ?? 0),
    ]);

    const [eventsByCategory, eventsByCity, eventsBySource, topEvents, eventsByDay, eventsByPublisher] = await Promise.all([
      prisma.$queryRawUnsafe<{ name: string; color: string; count: bigint }[]>(`
        SELECT c.name, c.color, COUNT(e.id)::int as count
        FROM events e
        LEFT JOIN categories c ON e.category_id = c.id
        WHERE e.status = 'approved'
        GROUP BY c.name, c.color
        ORDER BY count DESC
        LIMIT 12
      `),
      prisma.$queryRawUnsafe<{ city: string; count: bigint }[]>(`
        SELECT COALESCE(city, 'N/A') as city, COUNT(id)::int as count
        FROM events WHERE status = 'approved'
        GROUP BY city ORDER BY count DESC LIMIT 10
      `),
      prisma.$queryRawUnsafe<{ source_name: string; count: bigint }[]>(`
        SELECT COALESCE(source_name, 'N/A') as source_name, COUNT(id)::int as count
        FROM events WHERE is_auto_generated = true AND status = 'approved'
        GROUP BY source_name ORDER BY count DESC LIMIT 10
      `),
      prisma.$queryRawUnsafe<{ id: number; title: string; view_count: number; city: string; date: Date }[]>(`
        SELECT id, title, COALESCE(view_count, 0) as view_count, city, date
        FROM events WHERE status = 'approved'
        ORDER BY view_count DESC LIMIT 10
      `),
      prisma.$queryRawUnsafe<{ day: string; count: bigint }[]>(`
        SELECT TO_CHAR(created_at, 'YYYY-MM-DD') as day, COUNT(id)::int as count
        FROM events
        WHERE created_at >= $1
        GROUP BY day ORDER BY day
      `, thirtyDaysAgo),
      prisma.$queryRawUnsafe<{ name: string; role: string; count: bigint }[]>(`
        SELECT COALESCE(u.name, u.email, 'Anonimo') as name, u.role, COUNT(e.id)::int as count
        FROM events e
        LEFT JOIN users u ON e.created_by = u.id
        WHERE e.is_auto_generated = false
        GROUP BY u.name, u.email, u.role
        ORDER BY count DESC
        LIMIT 10
      `),
    ]);

    const eventsByDayMap = new Map<string, number>();
    const d = new Date(thirtyDaysAgo);
    while (d <= today) {
      eventsByDayMap.set(d.toISOString().split("T")[0], 0);
      d.setDate(d.getDate() + 1);
    }
    for (const row of eventsByDay) {
      eventsByDayMap.set(row.day, Number(row.count));
    }

    return helpers.jsonResponse({
      overview: {
        totalEvents,
        pendingEvents,
        approvedEvents,
        rejectedEvents,
        autoEvents,
        manualEvents,
        totalUsers,
        publishers,
        admins,
        totalSaved,
        totalAdClicks,
        totalViews,
      },
      eventsByCategory: eventsByCategory.map(r => ({ name: r.name || "N/A", color: r.color || "#888", count: Number(r.count) })),
      eventsByCity: eventsByCity.map(r => ({ city: r.city, count: Number(r.count) })),
      eventsBySource: eventsBySource.map(r => ({ name: r.source_name, count: Number(r.count) })),
      topEvents: topEvents.map(r => ({ id: r.id, title: r.title, views: r.view_count, city: r.city, date: r.date })),
      eventsByDay: Array.from(eventsByDayMap.entries()).map(([day, count]) => ({ day, count })),
      eventsByPublisher: eventsByPublisher.map(r => ({ name: r.name, role: r.role, count: Number(r.count) })),
    });
  } catch (err: any) {
    return Response.json({ error: err.message || "Internal error" }, { status: 500 });
  }
}
