import { NextRequest } from "next/server";

export async function GET(req: NextRequest) {
  try {
    const [helpers, { prisma }] = await Promise.all([
      import("@/lib/api-helpers"),
      import("@/lib/prisma"),
    ]);
    const { searchParams } = new URL(req.url);
    const category = searchParams.get("category");
    const province = searchParams.get("province");
    const city = searchParams.get("city");
    const time_period = searchParams.get("time_period");
    const dateFrom = searchParams.get("dateFrom");
    const dateTo = searchParams.get("dateTo");
    const search = searchParams.get("search");
    const page = Math.max(1, parseInt(searchParams.get("page") || "1"));
    const limit = Math.min(50, Math.max(1, parseInt(searchParams.get("limit") || "20")));
    const status = searchParams.get("status") || "approved";

    const where: any = { isPublished: true, status };
    where.date = { gte: dateFrom ? new Date(dateFrom) : new Date(new Date().toDateString()) };
    if (dateTo) where.date.lte = new Date(dateTo);
    if (category) {
      const slugs = category.split(',').map(s => s.trim()).filter(Boolean);
      if (slugs.length === 1) where.category = { slug: slugs[0] };
      else if (slugs.length > 1) where.category = { slug: { in: slugs } };
    }
    if (province) where.province = province;
    if (city) where.city = { contains: city, mode: "insensitive" };
    if (time_period) where.timePeriod = time_period;
    if (search) {
      where.OR = [
        { title: { contains: search, mode: "insensitive" } },
        { description: { contains: search, mode: "insensitive" } },
        { location: { contains: search, mode: "insensitive" } },
      ];
    }

    const [events, total] = await Promise.all([
      prisma.event.findMany({
        where,
        include: { category: true },
        orderBy: [{ date: "asc" }, { time: "asc" }],
        skip: (page - 1) * limit,
        take: limit,
      }),
      prisma.event.count({ where }),
    ]);

    const mapped = events.map((e: any) => ({
      ...e,
      is_new: Math.abs(Date.now() - e.createdAt.getTime()) / 86400000 <= 7,
      category_name: e.category?.name,
      category_slug: e.category?.slug,
      category_icon: e.category?.icon,
      category_color: e.category?.color,
      source_url: e.sourceUrl,
      source_name: e.sourceName,
      end_date: e.endDate,
      image_url: e.imageUrl,
      time_period: e.timePeriod,
      is_auto_generated: e.isAutoGenerated,
      is_published: e.isPublished,
    }));

    return helpers.jsonResponse({
      events: mapped,
      pagination: { page, limit, total, totalPages: Math.ceil(total / limit) },
    });
  } catch (err: any) {
    return handleError(err);
  }
}

export async function POST(req: NextRequest) {
  try {
    const [helpers, { prisma }] = await Promise.all([
      import("@/lib/api-helpers"),
      import("@/lib/prisma"),
    ]);
    const { user } = await helpers.requireAuth(req);
    const body = await req.json();
    if (!body.title || !body.category_id || !body.date) {
      return helpers.errorResponse("Titolo, categoria e data sono obbligatori");
    }
    const isAdmin = user.role === "admin" || user.role === "super_admin";
    const eventStatus = isAdmin ? "approved" : "pending";
    const event = await prisma.event.create({
      data: {
        title: body.title,
        description: body.description,
        categoryId: parseInt(body.category_id),
        date: new Date(body.date),
        endDate: body.end_date ? new Date(body.end_date) : null,
        time: body.time,
        location: body.location,
        address: body.address,
        city: body.city || "Latina",
        province: body.province || "LT",
        imageUrl: body.image_url,
        sourceUrl: body.source_url,
        sourceName: body.source_name,
        createdBy: user.id,
        status: eventStatus,
      },
    });
    return helpers.jsonResponse(event, 201);
  } catch (err: any) {
    return handleError(err);
  }
}

function handleError(err: any) {
  if (err.name === "AuthError") {
    return Response.json({ error: err.message }, { status: err.status || 401 });
  }
  console.error("API Error:", err);
  return Response.json({ error: "Errore interno del server" }, { status: 500 });
}
