import axios from 'axios';
import * as cheerio from 'cheerio';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function testScraper() {
  console.log('=== Testing MYmovies scraper locally ===\n');
  
  const res = await axios.get('https://www.mymovies.it/cinema/latina/programmazione/', {
    timeout: 15000,
    headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' },
  });

  const $ = cheerio.load(res.data);
  
  console.log('Page title:', $('title').text());
  console.log('Page length:', res.data.length);
  
  // Check film links
  const filmLinks = $('a[href*="/cinema/latina/provincia/?f="]');
  console.log(`Found ${filmLinks.length} film links`);
  
  filmLinks.each((_, el) => {
    const $link = $(el);
    const title = $link.text().trim();
    const href = $link.attr('href');
    if (title && title.length > 2 && !title.includes('Accedi') && !title.includes('Esci')) {
      console.log(`  Film: "${title}" -> ${href}`);
    }
  });
  
  // Check categories in DB
  const categories = await prisma.category.findMany({ select: { id: true, slug: true, name: true } });
  console.log('\nCategories in DB:');
  categories.forEach(c => console.log(`  ${c.slug} (id: ${c.id})`));
  
  // Check existing events
  const todayISO = new Date().toISOString().split('T')[0];
  const existing = await prisma.event.findMany({
    where: { 
      isAutoGenerated: true,
      date: { gte: new Date() }
    },
    select: { title: true, date: true, categoryId: true, sourceName: true },
    take: 10
  });
  console.log('\nExisting auto-generated events:');
  existing.forEach(e => console.log(`  ${e.title} | ${e.date} | catId: ${e.categoryId} | source: ${e.sourceName}`));
  
  await prisma.$disconnect();
}

main().catch(console.error);