import type { Metadata } from "next";

const SITE_URL = "https://portale-eventi-latina.vercel.app";
const DEFAULT_IMAGE = `${SITE_URL}/logo.png`;

async function getEvent(slug: string) {
  try {
    const { prisma } = await import("@/lib/prisma");
    await prisma.$executeRawUnsafe(`ALTER TABLE events ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE`);
    const isNumeric = /^\d+$/.test(slug);
    const event = await prisma.event.findUnique({
      where: isNumeric ? { id: parseInt(slug) } : { slug },
      include: { category: true },
    });
    return event;
  } catch (err) {
    console.error("[EventPage] Failed to fetch event:", err);
    return null;
  }
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const event = await getEvent(slug);

  if (!event) {
    return {
      title: "Evento non trovato | EventiNLatina",
      description: "L'evento che cerchi non esiste o è stato rimosso.",
    };
  }

  const imageUrl = event.imageUrl || DEFAULT_IMAGE;
  const description = event.description?.slice(0, 160) || `Scopri ${event.title} su EventiNLatina`;
  const eventUrl = `${SITE_URL}/events/${event.slug || event.id}`;

  return {
    title: `${event.title} | EventiNLatina`,
    description,
    openGraph: {
      title: event.title,
      description,
      url: eventUrl,
      siteName: "EventiNLatina",
      images: [
        {
          url: imageUrl,
          width: 1200,
          height: 630,
          alt: event.title,
        },
      ],
      locale: "it_IT",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: event.title,
      description,
      images: [imageUrl],
    },
    alternates: {
      canonical: eventUrl,
    },
  };
}

export default async function EventPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const event = await getEvent(slug);

  let initialEvent = null;
  if (event) {
    initialEvent = {
      ...event,
      date: event.date?.toISOString() || null,
      endDate: event.endDate?.toISOString() || null,
      createdAt: event.createdAt?.toISOString() || null,
      updatedAt: event.updatedAt?.toISOString() || null,
      category_name: event.category?.name,
      category_slug: event.category?.slug,
      category_icon: event.category?.icon,
      category_color: event.category?.color,
      source_url: event.sourceUrl,
      source_name: event.sourceName,
      end_date: event.endDate?.toISOString() || null,
      image_url: event.imageUrl,
      time_period: event.timePeriod,
      is_auto_generated: event.isAutoGenerated,
      is_published: event.isPublished,
      is_new: Math.abs(Date.now() - (event.createdAt?.getTime() || 0)) / 86400000 <= 7,
      slug: event.slug,
    };
  }

  const EventDetailClient = (await import("./event-detail")).default;
  return <EventDetailClient initialEvent={initialEvent} slug={slug} />;
}
