import { NextRequest } from "next/server";
import type { ScrapedEvent } from "@/lib/scraper/scraped-event";
import { getProvinceFromCity } from "@/lib/scraper/city-to-province";

async function getPrisma() {
  const mod = await import("@/lib/prisma");
  return mod.prisma;
}

function parseDateStr(dateStr: string): Date | null {
  const m = dateStr.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (m) return new Date(`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`);
  return null;
}

const OLD_TO_NEW_CATEGORY: Record<string, string> = {
  cat_music: 'musica',
  cat_theater: 'teatro',
  cat_culture: 'cultura',
  cat_sports: 'sport',
  cat_nature: 'natura',
  cat_trekking: 'trekking',
  cat_mountain: 'montagna',
  cat_excursion: 'escursioni',
  cat_daytrip: 'gite',
  cat_entertainment: 'spettacolo',
  cat_food: 'enogastronomia',
  cat_kids: 'bambini',
  cat_borghi: 'borghi',
  cat_benessere: 'benessere',
  cat_salute: 'salute',
  cat_rosa: 'rosa',
  cat_exhibition: 'mostre',
  cat_cinema: 'cinema',
  cat_sea: 'mare',
  cat_comingsoon_cinema: 'cinema',
  cat_comingsoon_sea: 'mare',
  // Direct slugs from scrapers
  cinema: 'cinema',
  mare: 'mare',
  escursioni: 'escursioni',
};

function dedupKey(e: ScrapedEvent): string {
  return e.title.toLowerCase().slice(0, 80) + e.date + e.city;
}

export async function POST(req: NextRequest) {
  const { jsonResponse, handleApiError, requireAdmin } = await import("@/lib/api-helpers");
  try {
    await requireAdmin(req);
    const { events, sourceName } = await req.json();
    if (!Array.isArray(events)) {
      return jsonResponse({ error: "Missing events array" }, 400);
    }

    const prisma = await getPrisma();

    // Ensure categories exist (auto-create missing ones)
    const requiredCategories = ['cinema', 'mare', 'escursioni', 'musica', 'teatro', 'cultura', 'sport', 'natura', 'trekking', 'montagna', 'gite', 'spettacolo', 'enogastronomia', 'bambini', 'borghi', 'benessere', 'salute', 'rosa', 'mostre'];
    const existingCats = await prisma.category.findMany({ where: { slug: { in: requiredCategories } }, select: { slug: true } });
    const existingSlugs = new Set(existingCats.map(c => c.slug));
    const missingSlugs = requiredCategories.filter(s => !existingSlugs.has(s));
    if (missingSlugs.length > 0) {
      await prisma.category.createMany({
        data: missingSlugs.map(slug => ({ slug, name: slug.charAt(0).toUpperCase() + slug.slice(1) })),
        skipDuplicates: true,
      });
      console.log(`[Ingest] Auto-created missing categories: ${missingSlugs.join(', ')}`);
    }

    const cats = await prisma.category.findMany({ select: { id: true, slug: true } });
    const catMap = new Map<string, number>();
    for (const c of cats) catMap.set(c.slug, c.id);

    const existing = await prisma.event.findMany({
      where: { isAutoGenerated: true },
      select: { title: true, date: true, city: true, sourceUrl: true },
    });
    const bySourceUrl = new Set<string>();
    const byDedup = new Set<string>();
    for (const e of existing) {
      if (e.sourceUrl) bySourceUrl.add(e.sourceUrl);
      if (e.title && e.date) {
        const d = e.date instanceof Date ? e.date.toISOString().split('T')[0] : '';
        byDedup.add(e.title.toLowerCase().slice(0, 80) + d + (e.city || ''));
      }
    }

let inserted = 0;
    for (const e of events) {
      // Don't deduplicate by source_url - each event from same source should be inserted
      // if (e.source_url && bySourceUrl.has(e.source_url)) continue;
      const key = dedupKey(e);
      if (byDedup.has(key)) continue;

      try {
        const slug = OLD_TO_NEW_CATEGORY[e.category_id] || e.category_id;
        const catId = catMap.get(slug);
        
        console.log(`[Ingest] "${e.title?.slice(0, 40)}" | category_id: ${e.category_id} -> slug: ${e.category_id} -> catId: ${catId}`);

        if (!catId) {
          console.warn(`[Ingest] Category not found for "${e.title?.slice(0, 30)}", skipping`);
          continue;
        }

        await prisma.event.create({
          data: {
            title: e.title.slice(0, 200),
            description: e.description?.slice(0, 2000) || null,
            categoryId: (() => {
              // Map old category IDs to new slugs, with fallback to direct slug
              const slug = OLD_TO_NEW_CATEGORY[e.category_id] || e.category_id;
              return catMap.get(slug) ?? null;
            })(),
            date: parseDateStr(e.date),
            endDate: e.end_date ? parseDateStr(e.end_date) : null,
            time: e.time || null,
            timePeriod: e.time_period || null,
            location: e.location || null,
            city: e.city || 'Latina',
            province: e.province || getProvinceFromCity(e.city || '') || null,
            region: 'Lazio',
            imageUrl: e.image_url || null,
            sourceUrl: e.source_url || null,
            sourceName: e.source_name || null,
            isAutoGenerated: true,
            isPublished: true,
          },
        });
        inserted++;
        bySourceUrl.add(e.source_url || '');
        byDedup.add(key);
      } catch (err: any) {
        console.error(`[Ingest] Insert error: ${err.message?.slice(0, 100)} for "${e.title?.slice(0, 40)}"`);
      }
    }

    return jsonResponse({
      message: `${inserted} eventi inseriti da ${sourceName || 'fonte locale'}`,
      found: events.length,
      inserted,
    });
  } catch (err) { return handleApiError(err); }
}
