import { ScrapedEvent } from './scraped-event';
import { runCentroItaliaScraper } from './centroItaliaScraper';
import { runLazioNascostoScraper } from './lazionascostoScraper';
import { runLatinaTodayScraper } from './latinatodayScraper';
import { runComuneLatinaScraper } from './comuneLatinaScraper';
import { runItinerariScraper } from './itinerariScraper';
import { runFattivivoScraper } from './fattivivoScraper';
import { scrapeTeatroIt } from './teatroItScraper';
import { runLazioEventiScraper } from './lazioeventiScraper';
import { runEventbriteScraper } from './eventbriteScraper';

const OLD_TO_NEW_CATEGORY: Record<string, string> = {
  cat_music: 'musica',
  cat_theater: 'teatro',
  cat_culture: 'cultura',
  cat_sports: 'sport',
  cat_nature: 'natura',
  cat_trekking: 'trekking',
  cat_mountain: 'montagna',
  cat_excursion: 'escursioni',
  cat_daytrip: 'gite',
  cat_entertainment: 'spettacolo',
  cat_food: 'enogastronomia',
  cat_kids: 'bambini',
  cat_borghi: 'borghi',
  cat_benessere: 'benessere',
  cat_salute: 'salute',
  cat_rosa: 'rosa',
  cat_exhibition: 'mostre',
};

const SCRAPER_REGISTRY: Record<string, { name: string; url: string; fn: () => Promise<ScrapedEvent[]> }> = {
  centroitalia: { name: 'CentroItaliaEvents', url: 'https://www.centroitaliaevents.it/', fn: runCentroItaliaScraper },
  lazionascosto: { name: 'LazioNascosto', url: 'https://www.lazionascosto.it/', fn: runLazioNascostoScraper },
  latinatoday: { name: 'LatinaToday', url: 'https://www.latinatoday.it/', fn: runLatinaTodayScraper },
  comunelatina: { name: 'Comune di Latina', url: 'https://www.comune.latina.it/', fn: runComuneLatinaScraper },
  itinerari: { name: 'Itinerari nell\'Arte', url: 'https://www.itinerarinellarte.it/', fn: runItinerariScraper },
  fattivivo: { name: 'FattiVivo', url: 'https://www.fattivivo.com/', fn: runFattivivoScraper },
  teatroIt: { name: 'Teatro.it', url: 'https://www.teatro.it/spettacoli/latina', fn: scrapeTeatroIt },
  lazioeventi: { name: 'LazioEventi.com', url: 'https://lazioeventi.com/oggi-nel-lazio', fn: runLazioEventiScraper },
  eventbrite: { name: 'Eventbrite', url: 'https://www.eventbrite.it/d/italy--latina/health--events', fn: runEventbriteScraper },
};

async function getPrisma() {
  const mod = await import("@/lib/prisma");
  return mod.prisma;
}

async function buildCategoryMap(): Promise<Map<string, number>> {
  const prisma = await getPrisma();
  const cats = await prisma.category.findMany({ select: { id: true, slug: true } });
  const map = new Map<string, number>();
  for (const c of cats) map.set(c.slug, c.id);
  return map;
}

function resolveCategoryId(categoryId: string, catMap: Map<string, number>): number | null {
  const slug = OLD_TO_NEW_CATEGORY[categoryId] || categoryId;
  return catMap.get(slug) ?? null;
}

function parseDateStr(dateStr: string): Date | null {
  const m = dateStr.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (m) return new Date(`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`);
  return null;
}

function dedupKey(e: ScrapedEvent): string {
  return e.title.toLowerCase().slice(0, 80) + e.date + e.city;
}

export interface ScraperResult {
  source: string;
  found: number;
  inserted: number;
}

export async function ensureScrapedSourcesTable() {
  const prisma = await getPrisma();
  try {
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS scraped_sources (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        url TEXT NOT NULL,
        type TEXT NOT NULL DEFAULT 'html',
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        selectors TEXT,
        city TEXT,
        province TEXT,
        category_id INTEGER,
        last_scraped_at TIMESTAMP WITH TIME ZONE,
        config_id INTEGER
      )
    `);
    console.log('[Scraper] Ensured scraped_sources table exists');
  } catch (err) {
    console.error('[Scraper] Failed to ensure scraped_sources table:', err);
  }
}

export async function ensureDefaultSources() {
  await ensureScrapedSourcesTable();
  const prisma = await getPrisma();
  for (const [type, info] of Object.entries(SCRAPER_REGISTRY)) {
    const existing = await prisma.scrapedSource.findFirst({ where: { type } });
    if (!existing) {
      await prisma.scrapedSource.create({
        data: { name: info.name, url: info.url, type, isActive: true },
      });
      console.log(`[Scraper] Created default source: ${info.name} (${type})`);
    }
  }
}

async function loadExistingEvents(): Promise<{ bySourceUrl: Set<string>; byDedup: Set<string> }> {
  const prisma = await getPrisma();
  const existing = await prisma.event.findMany({
    where: { isAutoGenerated: true },
    select: { title: true, date: true, city: true, sourceUrl: true },
  });
  const bySourceUrl = new Set<string>();
  const byDedup = new Set<string>();
  for (const e of existing) {
    if (e.sourceUrl) bySourceUrl.add(e.sourceUrl);
    if (e.title && e.date) {
      const d = e.date instanceof Date ? e.date.toISOString().split('T')[0] : '';
      byDedup.add(e.title.toLowerCase().slice(0, 80) + d + (e.city || ''));
    }
  }
  return { bySourceUrl, byDedup };
}

async function runSingleSource(
  name: string,
  scraperFn: () => Promise<ScrapedEvent[]>,
  existingEvents: { bySourceUrl: Set<string>; byDedup: Set<string> },
  catMap: Map<string, number>,
): Promise<ScraperResult> {
  console.log(`[Scraper] Source: ${name}...`);
  try {
    const events = await scraperFn();
    console.log(`[Scraper] ${name}: ${events.length} unique events scraped`);

    let inserted = 0;
    for (const e of events) {
      if (e.source_url && existingEvents.bySourceUrl.has(e.source_url)) continue;
      const key = dedupKey(e);
      if (existingEvents.byDedup.has(key)) continue;

      const prisma = await getPrisma();
      try {
        await prisma.event.create({
          data: {
            title: e.title.slice(0, 200),
            description: e.description?.slice(0, 2000) || null,
            categoryId: resolveCategoryId(e.category_id, catMap),
            date: parseDateStr(e.date),
            endDate: e.end_date ? parseDateStr(e.end_date) : null,
            time: e.time || null,
            timePeriod: e.time_period || null,
            location: e.location || null,
            city: e.city || 'Latina',
            province: e.province || 'LT',
            region: 'Lazio',
            imageUrl: e.image_url || null,
            sourceUrl: e.source_url || null,
            sourceName: e.source_name || null,
            isAutoGenerated: true,
            isPublished: true,
          },
        });
        inserted++;
        existingEvents.bySourceUrl.add(e.source_url || '');
        existingEvents.byDedup.add(key);
      } catch (err: any) {
        console.error(`[Scraper] Insert error: ${err.message?.slice(0, 100)} for "${e.title.slice(0, 40)}"`);
      }
    }

    console.log(`[Scraper] ${name}: ${inserted} new events inserted`);
    return { source: name, found: events.length, inserted };
  } catch (err: any) {
    console.error(`[Scraper] ${name} error: ${err.message?.slice(0, 100)}`);
    return { source: name, found: 0, inserted: 0 };
  }
}

export async function runScraper(sourceType?: string): Promise<ScraperResult[]> {
  console.log('[Scraper] Starting...');
  const prisma = await getPrisma();

  await ensureDefaultSources();

  const [catMap, existingEvents] = await Promise.all([
    buildCategoryMap(),
    loadExistingEvents(),
  ]);

  const results: ScraperResult[] = [];

  const where: any = { isActive: true };
  if (sourceType) where.type = sourceType;
  const sources = await prisma.scrapedSource.findMany({ where });

  for (const src of sources) {
    const registryEntry = SCRAPER_REGISTRY[src.type];
    if (!registryEntry) {
      console.log(`[Scraper] Unknown type "${src.type}" for source "${src.name}" — skipping`);
      continue;
    }
    const result = await runSingleSource(src.name, registryEntry.fn, existingEvents, catMap);
    results.push(result);
    try {
      await prisma.scrapedSource.update({ where: { id: src.id }, data: { lastScrapedAt: new Date() } });
    } catch (e: any) {
      console.error(`[Scraper] Failed to update lastScrapedAt for ${src.name}: ${e.message?.slice(0, 100)}`);
    }
  }

  // Fallback: if sourceType specified but no DB sources were found, try registry directly
  if (sourceType && sources.length === 0) {
    const entry = SCRAPER_REGISTRY[sourceType];
    if (entry) {
      console.log(`[Scraper] Running ${entry.name} directly from registry (no DB source record found)`);
      const result = await runSingleSource(entry.name, entry.fn, existingEvents, catMap);
      results.push(result);
    } else {
      console.log(`[Scraper] Unknown source type "${sourceType}" — not in registry either`);
    }
  }

  // Fallback: if running all sources and none from DB, run all from registry
  if (!sourceType && sources.length === 0) {
    console.log('[Scraper] No DB sources found, running all from registry directly');
    for (const [type, entry] of Object.entries(SCRAPER_REGISTRY)) {
      const result = await runSingleSource(entry.name, entry.fn, existingEvents, catMap);
      results.push(result);
    }
  }

  console.log(`[Scraper] Done. Results: ${JSON.stringify(results)}`);
  return results;
}

export async function previewScraper(): Promise<ScrapedEvent[]> {
  console.log('[Scraper] Preview mode - scraping without saving...');

  const all: ScrapedEvent[] = [];
  const seen = new Set<string>();

  async function collect(name: string, scraperFn: () => Promise<ScrapedEvent[]>): Promise<void> {
    try {
      const events = await scraperFn();
      for (const e of events) {
        const key = dedupKey(e);
        if (!seen.has(key)) {
          seen.add(key);
          all.push(e);
        }
      }
      console.log(`[Scraper] ${name}: ${events.length} events`);
    } catch (err: any) {
      console.error(`[Scraper] ${name} error: ${err.message?.slice(0, 100)}`);
    }
  }

  await collect('CentroItaliaEvents', runCentroItaliaScraper);
  await collect('LazioNascosto', runLazioNascostoScraper);
  await collect('LatinaToday', runLatinaTodayScraper);
  await collect('Comune di Latina', runComuneLatinaScraper);
  await collect('Itinerari nell\'Arte', runItinerariScraper);
  await collect('FattiVivo', runFattivivoScraper);
  await collect('Teatro.it', scrapeTeatroIt);
  await collect('LazioEventi.com', runLazioEventiScraper);
  await collect('Eventbrite', runEventbriteScraper);

  console.log(`[Scraper] Preview: ${all.length} unique events total`);
  return all;
}
