import { ScrapedEvent } from './scraped-event';
import { runCentroItaliaScraper } from './centroItaliaScraper';
import { runLazioNascostoScraper } from './lazionascostoScraper';
import { runLatinaTodayScraper } from './latinatodayScraper';

const OLD_TO_NEW_CATEGORY: Record<string, string> = {
  cat_music: 'musica',
  cat_theater: 'teatro',
  cat_culture: 'cultura',
  cat_sports: 'sport',
  cat_nature: 'natura',
  cat_trekking: 'trekking',
  cat_mountain: 'montagna',
  cat_daytrip: 'gite',
  cat_entertainment: 'spettacolo',
  cat_food: 'enogastronomia',
  cat_kids: 'bambini',
};

async function getPrisma() {
  const mod = await import("@/lib/prisma");
  return mod.prisma;
}

async function buildCategoryMap(): Promise<Map<string, number>> {
  const prisma = await getPrisma();
  const cats = await prisma.category.findMany({ select: { id: true, slug: true } });
  const map = new Map<string, number>();
  for (const c of cats) map.set(c.slug, c.id);
  return map;
}

function resolveCategoryId(categoryId: string, catMap: Map<string, number>): number | null {
  const slug = OLD_TO_NEW_CATEGORY[categoryId] || categoryId;
  return catMap.get(slug) ?? null;
}

function parseDateStr(dateStr: string): Date | null {
  const m = dateStr.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (m) return new Date(`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`);
  return null;
}

function dedupKey(e: ScrapedEvent): string {
  return e.title.toLowerCase().slice(0, 80) + e.date + e.city;
}

export interface ScraperResult {
  source: string;
  found: number;
  inserted: number;
}

export async function runScraper(): Promise<ScraperResult[]> {
  console.log('[Scraper] Starting...');

  const [catMap, existingEvents] = await Promise.all([
    buildCategoryMap(),
    (async () => {
      const prisma = await getPrisma();
      const existing = await prisma.event.findMany({
        where: { isAutoGenerated: true },
        select: { title: true, date: true, city: true, sourceUrl: true },
      });
      const bySourceUrl = new Set<string>();
      const byDedup = new Set<string>();
      for (const e of existing) {
        if (e.sourceUrl) bySourceUrl.add(e.sourceUrl);
        if (e.title && e.date) {
          const d = e.date instanceof Date ? e.date.toISOString().split('T')[0] : '';
          byDedup.add(e.title.toLowerCase().slice(0, 80) + d + (e.city || ''));
        }
      }
      return { bySourceUrl, byDedup };
    })(),
  ]);

  const results: ScraperResult[] = [];

  async function runSource(name: string, scraperFn: () => Promise<ScrapedEvent[]>): Promise<void> {
    console.log(`[Scraper] Source: ${name}...`);
    try {
      const events = await scraperFn();
      console.log(`[Scraper] ${name}: ${events.length} unique events scraped`);

      let inserted = 0;
      for (const e of events) {
        if (e.source_url && existingEvents.bySourceUrl.has(e.source_url)) continue;
        const key = dedupKey(e);
        if (existingEvents.byDedup.has(key)) continue;

        const prisma = await getPrisma();
        try {
          await prisma.event.create({
            data: {
              title: e.title.slice(0, 200),
              description: e.description?.slice(0, 2000) || null,
              categoryId: resolveCategoryId(e.category_id, catMap),
              date: parseDateStr(e.date),
              endDate: e.end_date ? parseDateStr(e.end_date) : null,
              time: e.time || null,
              timePeriod: e.time_period || null,
              location: e.location || null,
              city: e.city || 'Latina',
              province: e.province || 'LT',
              region: 'Lazio',
              imageUrl: e.image_url || null,
              sourceUrl: e.source_url || null,
              sourceName: e.source_name || null,
              isAutoGenerated: true,
              isPublished: true,
            },
          });
          inserted++;
          existingEvents.bySourceUrl.add(e.source_url || '');
          existingEvents.byDedup.add(key);
        } catch (err: any) {
          console.error(`[Scraper] Insert error: ${err.message?.slice(0, 100)} for "${e.title.slice(0, 40)}"`);
        }
      }

      results.push({ source: name, found: events.length, inserted });
      console.log(`[Scraper] ${name}: ${inserted} new events inserted`);
    } catch (err: any) {
      console.error(`[Scraper] ${name} error: ${err.message?.slice(0, 100)}`);
      results.push({ source: name, found: 0, inserted: 0 });
    }
  }

  await runSource('CentroItaliaEvents', runCentroItaliaScraper);
  await runSource('LazioNascosto', runLazioNascostoScraper);
  await runSource('LatinaToday', runLatinaTodayScraper);

  console.log(`[Scraper] Done. Results: ${JSON.stringify(results)}`);
  return results;
}

export async function previewScraper(): Promise<ScrapedEvent[]> {
  console.log('[Scraper] Preview mode - scraping without saving...');

  const all: ScrapedEvent[] = [];
  const seen = new Set<string>();

  async function collect(name: string, scraperFn: () => Promise<ScrapedEvent[]>): Promise<void> {
    try {
      const events = await scraperFn();
      for (const e of events) {
        const key = dedupKey(e);
        if (!seen.has(key)) {
          seen.add(key);
          all.push(e);
        }
      }
      console.log(`[Scraper] ${name}: ${events.length} events`);
    } catch (err: any) {
      console.error(`[Scraper] ${name} error: ${err.message?.slice(0, 100)}`);
    }
  }

  await collect('CentroItaliaEvents', runCentroItaliaScraper);
  await collect('LazioNascosto', runLazioNascostoScraper);
  await collect('LatinaToday', runLatinaTodayScraper);

  console.log(`[Scraper] Preview: ${all.length} unique events total`);
  return all;
}
