import { NextRequest } from "next/server";
import { jsonResponse, handleApiError, requireAdmin } from "@/lib/api-helpers";

export async function GET(req: NextRequest) {
  try {
    await requireAdmin(req);
    const { prisma } = await import("@/lib/prisma");

    const { ensureDefaultSources } = await import("@/lib/scraper/engine");
    await ensureDefaultSources();

    const [scrapedSources, totalEvents, autoEvents, bySource] = await Promise.all([
      prisma.scrapedSource.findMany({
        orderBy: { id: 'asc' },
      }),
      prisma.event.count(),
      prisma.event.count({ where: { isAutoGenerated: true } }),
      prisma.event.groupBy({
        by: ['sourceName'],
        where: { isAutoGenerated: true, sourceName: { not: null } },
        _count: true,
      }),
    ]);

    const sources = scrapedSources.map(s => {
      const stats = bySource.find(b => b.sourceName === s.name);
      return {
        ...s,
        eventCount: stats?._count ?? 0,
      };
    });

    const eventCountBySource = bySource.map(s => ({
      name: s.sourceName,
      count: s._count,
    }));

    return jsonResponse({ sources, totalEvents, autoEvents, eventCountBySource });
  } catch (err) { return handleApiError(err); }
}

export async function PUT(req: NextRequest) {
  try {
    await requireAdmin(req);
    const { prisma } = await import("@/lib/prisma");
    const body = await req.json();
    const { id, ...data } = body;

    if (id === -1) {
      if (!data.name?.trim() || !data.url?.trim()) {
        return jsonResponse({ error: "Nome e URL sono obbligatori" }, 400);
      }
      const created = await prisma.scrapedSource.create({
        data: { name: data.name.trim(), url: data.url.trim(), type: data.type?.trim() || "" },
      });
      return jsonResponse(created);
    }

    if (!id) return jsonResponse({ error: "id required" }, 400);

    const updated = await prisma.scrapedSource.update({
      where: { id },
      data: {
        name: data.name,
        url: data.url,
        isActive: data.isActive,
        type: data.type,
        city: data.city,
        province: data.province,
        categoryId: data.categoryId,
        selectors: data.selectors,
      },
    });
    return jsonResponse(updated);
  } catch (err) { return handleApiError(err); }
}

export async function DELETE(req: NextRequest) {
  try {
    await requireAdmin(req);
    const body = await req.json().catch(() => ({}));
    const { id } = body;
    if (!id) return jsonResponse({ error: "id required" }, 400);

    const { prisma } = await import("@/lib/prisma");
    await prisma.scrapedSource.delete({ where: { id } });
    return jsonResponse({ success: true });
  } catch (err) { return handleApiError(err); }
}
