import { NextRequest } from "next/server";
import { jsonResponse, handleApiError, requireAdmin } from "@/lib/api-helpers";

export async function GET(req: NextRequest) {
  try {
    await requireAdmin(req);
    const { prisma } = await import("@/lib/prisma");

    const [totalEvents, autoEvents, bySource] = await Promise.all([
      prisma.event.count(),
      prisma.event.count({ where: { isAutoGenerated: true } }),
      prisma.event.groupBy({
        by: ['sourceName'],
        where: { isAutoGenerated: true, sourceName: { not: null } },
        _count: true,
      }),
    ]);

    const sources = bySource.map(s => ({
      name: s.sourceName,
      count: s._count,
    }));

    return jsonResponse({ totalEvents, autoEvents, sources });
  } catch (err) { return handleApiError(err); }
}
