import { NextRequest } from "next/server";
import { jsonResponse, handleApiError, requireAdmin } from "@/lib/api-helpers";

export async function POST(req: NextRequest) {
  try {
    await requireAdmin(req);
    const { prisma } = await import("@/lib/prisma");

    const result = await prisma.event.deleteMany({
      where: {
        isAutoGenerated: true,
        date: new Date("2026-01-01T00:00:00Z"),
      },
    });

    return jsonResponse({ message: "Pulizia completata", deleted: result.count });
  } catch (err) { return handleApiError(err); }
}
