import { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  const { jsonResponse, handleApiError, requireAdmin } = await import("@/lib/api-helpers");
  try {
    await requireAdmin(req);
    const { prisma } = await import("@/lib/prisma");

    const result = await prisma.event.deleteMany({
      where: {
        isAutoGenerated: true,
        date: new Date("2026-01-01T00:00:00Z"),
      },
    });

    return jsonResponse({ message: "Pulizia completata", deleted: result.count });
  } catch (err) { return handleApiError(err); }
}
