import { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  const { jsonResponse, handleApiError, requireAdmin } = await import("@/lib/api-helpers");
  try {
    await requireAdmin(req);
    const { prisma } = await import("@/lib/prisma");
    const body = await req.json().catch(() => ({}));

    let whereClause: any = { isAutoGenerated: true };

    if (body.before) {
      whereClause.date = { lt: new Date(body.before) };
    } else {
      whereClause.date = { lt: new Date() };
    }

    if (body.category) {
      const cat = await prisma.category.findUnique({ where: { slug: body.category } });
      if (cat) whereClause.categoryId = cat.id;
    }

    const result = await prisma.event.deleteMany({ where: whereClause });

    return jsonResponse({ message: "Pulizia completata", deleted: result.count });
  } catch (err) { return handleApiError(err); }
}
