export const CATEGORY_LIST = [
  { slug: 'musica', name: 'Musica' },
  { slug: 'teatro', name: 'Teatro' },
  { slug: 'cultura', name: 'Cultura' },
  { slug: 'mostre', name: 'Mostre' },
  { slug: 'sport', name: 'Sport' },
  { slug: 'natura', name: 'Natura' },
  { slug: 'trekking', name: 'Trekking' },
  { slug: 'montagna', name: 'Montagna' },
  { slug: 'escursioni', name: 'Escursioni' },
  { slug: 'gite', name: 'Gite' },
  { slug: 'spettacolo', name: 'Spettacolo' },
  { slug: 'enogastronomia', name: 'Enogastronomia' },
  { slug: 'bambini', name: 'Bambini' },
  { slug: 'borghi', name: 'Borghi e dintorni' },
  { slug: 'benessere', name: 'Benessere' },
  { slug: 'salute', name: 'Salute' },
  { slug: 'rosa', name: 'Eventi in Rosa' },
];
